import './Base.css'

function Base_content() {
    return(
        <div>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
            <p>Oi</p>
        </div>
    )
}

export default Base_content;